name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
        postgres:
          image: postgres:13
          ports:
            - 5432:5432
          env:
            POSTGRES_DB: grit_tych_rpp_finance_bd
            POSTGRES_USER: grit_tych_rpp_finance
            POSTGRES_PASSWORD: 123
          options: >-
            --health-cmd="pg_isready -U grit_tych_finance" 
            --health-interval=10s 
            --health-timeout=5s 
            --health-retries=5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Unit Tests
        run: pytest

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=postgresql://grit_tych_rpp_finance:123@localhost:5432/grit_tych_rpp_finance_bd" >> $GITHUB_ENV  

  # Job: Security Check with 
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Security Scan
        run: bandit -r .  # Scan the project recursively

  # Job: Generate Changelog
  # changelog:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'

  #     - name: Generate Changelog
  #       run: |
  #         chmod +x generate_changelog.sh
  #         ./generate_changelog.sh

  #     - name: Create docs directory if not exists
  #       run: |
  #         mkdir -p docs

  #     - name: Save Changelog
  #       run: |
  #         mv changelog.md docs/changelog.md

  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Generate Changelog
        run: |
          chmod +x generate_changelog.sh
          ./generate_changelog.sh

      - name: Add changelog to git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add changelog.md
          git commit -m "Update changelog" --allow-empty

      - name: Push to gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true

  # Job: Deploy to GitHub Pages
  # deploy:
  #   needs: changelog
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./docs
          

  
