name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' # Или нужная вам версия

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest # Предполагается, что у вас есть тесты

      - name: Security check with bandit
        run: bandit -r .

      - name: Generate changelog
        run: ./generate_changelog.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Директория с changelog.md
