name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job: Run Unit Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Unit Tests
        run: pytest

  # Job: Security Check with Bandit
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r .  # Scan the entire repository

  # Job: Generate Changelog
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run changelog script
        run: |
          chmod +x generate_changelog.sh
          ./generate_changelog.sh

      - name: Save changelog
        run: |
          mv changelog.md docs/

  # Job: Deploy to GitHub Pages
  deploy:
    needs: changelog  # Ensure changelog is generated first
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
